#!/bin/bash

# echo "================================================"
# echo "Running Radiosity simulations..."
# echo "================================================"
# echo "> mono"
# ../../venv/bin/python3 demo_radiosity.py --mic mono --output_dir "outputs_audios/radiosity/mono"
# echo "> ambisonic (1st order)"
# ../../venv/bin/python3 demo_radiosity.py --mic ambisonic --ambisonic_order 1st_order --output_dir "outputs_audios/radiosity/ambisonic_1st"
# echo "> ambisonic (2nd order)"
# ../../venv/bin/python3 demo_radiosity.py --mic ambisonic --ambisonic_order 2nd_order --output_dir "outputs_audios/radiosity/ambisonic_2nd"
# echo "> binaural"
# ../../venv/bin/python3 demo_radiosity.py --mic ambisonic --ambisonic_order binaural --output_dir "outputs_audios/radiosity/binaural"

# echo "================================================"
# echo "Running ISM simulations..."
# echo "================================================"
# echo "> mono"
# ../../venv/bin/python3 demo_ism.py --mic mono --output_dir "outputs_audios/ism/mono"
# echo "> ambisonic (1st order)"
# ../../venv/bin/python3 demo_ism.py --mic ambisonic --ambisonic_order 1st_order --output_dir "outputs_audios/ism/ambisonic_1st"
# echo "> ambisonic (2nd order)"
# ../../venv/bin/python3 demo_ism.py --mic ambisonic --ambisonic_order 2nd_order --output_dir "outputs_audios/ism/ambisonic_2nd"
# echo "> binaural"
# ../../venv/bin/python3 demo_ism.py --mic ambisonic --ambisonic_order binaural --output_dir "outputs_audios/ism/binaural"

# echo "================================================"
# echo "Running Spectral simulations..."
# echo "================================================"
# echo "> ambisonic (1st order)"
# ../../venv/bin/python3 demo_spectral.py --mic ambisonic --ambisonic_order 1st_order --output_dir "outputs_audios/spectral/ambisonic_1st"
# echo "> mono"
# ../../venv/bin/python3 demo_spectral.py --mic mono --output_dir "outputs_audios/spectral/mono"
# echo "> ambisonic (2nd order)"
# ../../venv/bin/python3 demo_spectral.py --mic ambisonic --ambisonic_order 2nd_order --output_dir "outputs_audios/spectral/ambisonic_2nd"
# echo "> binaural"
# ../../venv/bin/python3 demo_spectral.py --mic ambisonic --ambisonic_order binaural --output_dir "outputs_audios/spectral/binaural"

echo "================================================"
echo "Running Raytracing simulations..."
echo "================================================"
echo "> mono"
../../venv/bin/python3 demo_raytracing.py --mic mono --output_dir "outputs_audios/raytracing/mono"
echo "> ambisonic (1st order)"
../../venv/bin/python3 demo_raytracing.py --mic ambisonic --ambisonic_order 1st_order --output_dir "outputs_audios/raytracing/ambisonic_1st"
echo "> ambisonic (2nd order)"
../../venv/bin/python3 demo_raytracing.py --mic ambisonic --ambisonic_order 2nd_order --output_dir "outputs_audios/raytracing/ambisonic_2nd"
echo "> binaural"
../../venv/bin/python3 demo_raytracing.py --mic ambisonic --ambisonic_order binaural --output_dir "outputs_audios/raytracing/binaural"

# echo "================================================"
# echo "Running Hybrid simulations..."
# echo "================================================"
# echo "> mono"
# ../../venv/bin/python3 demo_hybrid.py --mic mono --output_dir "outputs_audios/hybrid/mono"
# echo "> ambisonic (1st order)"
# ../../venv/bin/python3 demo_hybrid.py --mic ambisonic --ambisonic_order 1st_order --output_dir "outputs_audios/hybrid/ambisonic_1st"
# echo "> ambisonic (2nd order)"
# ../../venv/bin/python3 demo_hybrid.py --mic ambisonic --ambisonic_order 2nd_order --output_dir "outputs_audios/hybrid/ambisonic_2nd"
# echo "> binaural"
# ../../venv/bin/python3 demo_hybrid.py --mic ambisonic --ambisonic_order binaural --output_dir "outputs_audios/hybrid/binaural"
